##############################################
# Server Configuration
##############################################
server.port=${SERVER_PORT:8081}

##############################################
# Application Configuration
##############################################
spring.application.name=${SPRING_APPLICATION_NAME:user-service}

##############################################
# PostgreSQL
##############################################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/user_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:9398789744@Kk}
spring.jpa.hibernate.ddl-auto=update

##############################################
# Keycloak
##############################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/Ecommerce-Users}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI}
security.jwt.issuer=${KEYCLOAK_ISSUER}
keycloak.server-url=${KEYCLOAK_SERVER_URL:http://keycloak:8080}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:Ecommerce-Users}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:ecommerce-backend-client}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:ytZxu93ZLVA8E02DHyCzZIhjpSZIgzsp}
keycloak.app.realm=${KEYCLOAK_APP_REALM:Ecommerce-Users}

##############################################
# JWT
##############################################
jwt.secret=${JWT_SECRET:jklLopvE/x/NhvbA9JtAqYBdZBGCh5Hb+0rj4XwBfJk=}
jwt.expiration=${JWT_EXPIRATION:1200000}

##############################################
# Eureka
##############################################
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${HOSTNAME:user-service}

##############################################
# Frontend
##############################################
frontend.url=${FRONTEND_URL:http://frontend:80}

##############################################
# Logging
##############################################
logging.pattern.console=%d{HH:mm:ss} %-5level ${spring.application.name} - %msg%n
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG